# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'bacooNewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  pod 'Firebase/Core', '~> 5.20.2'
  pod 'Firebase/Messaging', '~> 5.20.2'

  pod 'GoogleIDFASupport', '~> 3.14.0'

 
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'bacooNewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


